// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rastreo.Api.Data;

#nullable disable

namespace Rastreo.Api.Migrations
{
    [DbContext(typeof(RastreoDbContext))]
    partial class RastreoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RASTREO")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rastreo.Api.Models.Enfermedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("TipoCampo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Enfermedades", "RASTREO");
                });

            modelBuilder.Entity("Rastreo.Api.Models.Granja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propietario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("Granjas", "RASTREO");
                });

            modelBuilder.Entity("Rastreo.Api.Models.InformeEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Asunto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DestinatariosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMensaje")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("OK");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InformeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioEnvio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("InformeId");

                    b.ToTable("InformeEnvios", "RASTREO");
                });

            modelBuilder.Entity("Rastreo.Api.Models.InformeEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadEnvios")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Consecutivo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("ConsolidacionPct")
                        .HasColumnType("float");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("GENERADO");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("GranjaId")
                        .HasColumnType("int");

                    b.Property<double>("Idn")
                        .HasColumnType("float");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("BAJO");

                    b.Property<byte[]>("PdfBinario")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("PdfPesoBytes")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodoDesde")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodoEtiqueta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodoHasta")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrevalenciaPct")
                        .HasColumnType("float");

                    b.Property<string>("ResponsableTecnico")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalEvaluados")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioGeneracion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Consecutivo")
                        .IsUnique();

                    b.HasIndex("FechaGeneracion");

                    b.HasIndex("GranjaId");

                    b.HasIndex("GranjaId", "PeriodoDesde", "PeriodoHasta");

                    b.ToTable("InformesEvaluacion", "RASTREO", t =>
                        {
                            t.HasCheckConstraint("CK_Informe_Estado", "[Estado] IN ('BORRADOR','GENERADO','ENVIADO','ERROR','ANULADO')");

                            t.HasCheckConstraint("CK_Informe_Riesgo", "[NivelRiesgo] IN ('BAJO','MEDIO','ALTO','CRITICO')");
                        });
                });

            modelBuilder.Entity("Rastreo.Api.Models.Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DetalleActualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BORRADOR");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GranjaId")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasoActual")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("UsaVacunas")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioUltimaModificacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("GranjaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Registros", "RASTREO", t =>
                        {
                            t.HasCheckConstraint("CK_Registros_Estado", "[Estado] IN ('BORRADOR','EN_PROCESO','FINALIZADO','ANULADO')");
                        });
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AbscesoNodulo")
                        .HasColumnType("bit");

                    b.Property<byte>("Accesorio")
                        .HasColumnType("tinyint");

                    b.Property<string>("AgudaCronica")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<byte>("ApicalDerecho")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ApicalIzquierdo")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CardiacoDerecho")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CardiacoIzquierdo")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DiafragmaticoDerecho")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DiafragmaticoIzquierdo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BORRADOR");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Moco")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroLinea")
                        .HasColumnType("int");

                    b.Property<string>("PasoActual")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PericardioEngrosado")
                        .HasColumnType("bit");

                    b.Property<bool>("Pericarditis")
                        .HasColumnType("bit");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SPES")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.ToTable("RegistroDetalle", "RASTREO", t =>
                        {
                            t.HasCheckConstraint("CK_Detalle_AC", "[AgudaCronica] IS NULL OR [AgudaCronica] IN ('A','C','AC')");

                            t.HasCheckConstraint("CK_Detalle_AD", "[ApicalDerecho] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Detalle_AL", "[ApicalIzquierdo] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Detalle_CD", "[CardiacoDerecho] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Detalle_CL", "[CardiacoIzquierdo] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Detalle_DD", "[DiafragmaticoDerecho] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Detalle_DL", "[DiafragmaticoIzquierdo] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Detalle_L", "[Accesorio] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Detalle_SPES", "[SPES] BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroDetalleEnfermedadValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnfermedadId")
                        .HasColumnType("int");

                    b.Property<Guid>("RegistroDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ValorBooleano")
                        .HasColumnType("bit");

                    b.Property<byte?>("ValorNumero")
                        .HasColumnType("tinyint");

                    b.Property<string>("ValorTexto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EnfermedadId");

                    b.HasIndex("RegistroDetalleId", "EnfermedadId")
                        .IsUnique();

                    b.ToTable("RegistroDetalleEnfermedadValores", "RASTREO", t =>
                        {
                            t.HasCheckConstraint("CK_DetalleEnf_ValorNumero", "[ValorNumero] IS NULL OR [ValorNumero] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_DetalleEnf_ValorTexto", "[ValorTexto] IS NULL OR [ValorTexto] IN ('A','C','AC')");
                        });
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroDetalleFoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoBinario")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FotoMimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FotoNombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FotoPesoBytes")
                        .HasColumnType("int");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("RegistroDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegistroDetalleId", "Orden")
                        .IsUnique();

                    b.ToTable("RegistroDetalleFoto", "RASTREO", t =>
                        {
                            t.HasCheckConstraint("CK_DetalleFoto_Orden", "[Orden] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroVacuna", b =>
                {
                    b.Property<Guid>("RegistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VacunaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("RegistroId", "VacunaId");

                    b.HasIndex("VacunaId");

                    b.ToTable("RegistroVacunas", "RASTREO");
                });

            modelBuilder.Entity("Rastreo.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("USUARIO");

                    b.Property<DateTime?>("SesionExpira")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SesionToken")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", "RASTREO");
                });

            modelBuilder.Entity("Rastreo.Api.Models.Vacuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Laboratorio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Vacunas", "RASTREO");
                });

            modelBuilder.Entity("Rastreo.Api.Models.InformeEnvio", b =>
                {
                    b.HasOne("Rastreo.Api.Models.InformeEvaluacion", "Informe")
                        .WithMany("Envios")
                        .HasForeignKey("InformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Informe");
                });

            modelBuilder.Entity("Rastreo.Api.Models.InformeEvaluacion", b =>
                {
                    b.HasOne("Rastreo.Api.Models.Granja", "Granja")
                        .WithMany()
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Granja");
                });

            modelBuilder.Entity("Rastreo.Api.Models.Registro", b =>
                {
                    b.HasOne("Rastreo.Api.Models.Granja", "Granja")
                        .WithMany()
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rastreo.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Granja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroDetalle", b =>
                {
                    b.HasOne("Rastreo.Api.Models.Registro", "Registro")
                        .WithMany("Detalles")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroDetalleEnfermedadValor", b =>
                {
                    b.HasOne("Rastreo.Api.Models.Enfermedad", "Enfermedad")
                        .WithMany()
                        .HasForeignKey("EnfermedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rastreo.Api.Models.RegistroDetalle", "RegistroDetalle")
                        .WithMany("EnfermedadesValores")
                        .HasForeignKey("RegistroDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermedad");

                    b.Navigation("RegistroDetalle");
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroDetalleFoto", b =>
                {
                    b.HasOne("Rastreo.Api.Models.RegistroDetalle", "RegistroDetalle")
                        .WithMany("Fotos")
                        .HasForeignKey("RegistroDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroDetalle");
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroVacuna", b =>
                {
                    b.HasOne("Rastreo.Api.Models.Registro", "Registro")
                        .WithMany("Vacunas")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rastreo.Api.Models.Vacuna", "Vacuna")
                        .WithMany()
                        .HasForeignKey("VacunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Registro");

                    b.Navigation("Vacuna");
                });

            modelBuilder.Entity("Rastreo.Api.Models.InformeEvaluacion", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("Rastreo.Api.Models.Registro", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Vacunas");
                });

            modelBuilder.Entity("Rastreo.Api.Models.RegistroDetalle", b =>
                {
                    b.Navigation("EnfermedadesValores");

                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
